packageExtensions:
  "@linaria/babel-preset@*":
    dependencies:
      "@babel/plugin-proposal-export-namespace-from": "*"
      "@babel/plugin-transform-modules-commonjs": "*"
  "@linaria/webpack4-loader@*":
    dependencies:
      "@babel/core": "*"
      webpack: ^4.0.0
  "@mdx-js/loader@*":
    dependencies:
      react: ^16.13.0
  "@storybook/addon-essentials@*":
    dependencies:
      "@storybook/components": ^6.3.0
      "@storybook/core-events": ^6.3.0
      "@storybook/theming": ^6.3.0
  "@storybook/core@*":
    dependencies:
      webpack: ^4.0.0
  "@storybook/csf-tools@*":
    dependencies:
      "@babel/core": "*"
  babel-loader@*:
    dependencies:
      webpack: ^4.0.0
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: ^4.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
