yarnPath: .yarn/releases/yarn-3.1.0.cjs
packageExtensions:
  "@linaria/babel-preset@*":
    dependencies:
      "@babel/plugin-proposal-export-namespace-from": "*"
      "@babel/plugin-transform-modules-commonjs": "*"
  'babel-loader@*':
    dependencies:
      "webpack": "^4.0.0"
  '@linaria/webpack4-loader@*':
    dependencies:
      "webpack": "^4.0.0"
      "@babel/core": "*"
