yarnPath: .yarn/releases/yarn-3.1.0.cjs
packageExtensions:
  "@linaria/babel-preset@*":
    dependencies:
      "@babel/plugin-proposal-export-namespace-from": "*"
      "@babel/plugin-transform-modules-commonjs": "*"
